apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mongo.fullname" . }}
  labels:
    app: reddit
    component: mongo
    release: {{ .Release.Name }}
    post-db: "true"
    comment-db: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: mongo
      release: {{ .Release.Name }}
  template:
    metadata:
      name: mongo
      labels:
        app: reddit
        component: mongo
        release: {{ .Release.Name }}
        post-db: "true"
        comment-db: "true"
    spec:
      containers:
      - image: mongo:3.2
        name: mongo
        volumeMounts:
        - name: mongo-gce-pd-storage
          mountPath: /data/db
        # resources:
        #   limits:
        #     cpu: 300m
        #     memory: 400Mi
        #   requests:
        #     cpu: 200m
        #     memory: 200Mi
      volumes:
      - name: mongo-gce-pd-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
