web:
  image: 'gitlab/gitlab-ce:latest'
  restart: always
  hostname: '158.160.47.242'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://158.160.47.242'
  ports:
    - '80:80'
    - '443:443'
    - '2222:22'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
