---
- name: Install pre-required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop: "{{ required_packages }}"

- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_repo_key }}"
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "{{ docker_repo }}"
    state: present

- name: Install docker packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    force: true
  loop: "{{ docker_packages }}"

- name: Docker user in groups
  user:
    name: "{{ docker_user }}"
    groups: "{{ docker_group }}"
    append: true
